#import <AppKit/AppKit.h>
#import <UserNotifications/UserNotifications.h>
#include <netinet/in.h>
#include <sys/socket.h>

extern const int UplinCHeartbeatPort;

@class UplinCToggleMenuItemView;

@interface UplinCApp : NSObject <NSApplicationDelegate, UNUserNotificationCenterDelegate, NSNetServiceDelegate, NSNetServiceBrowserDelegate, NSMenuDelegate>
@property NSStatusItem *statusItem;
@property NSMenuItem *statusMenuItem;
@property NSMenuItem *lastCheckMenuItem;
@property NSMenuItem *logStatusMenuItem;
@property NSMenuItem *tcpStatusMenuItem;
@property NSMenuItem *heartbeatStatusMenuItem;
@property NSMenuItem *versionMenuItem;
@property NSMenuItem *machinesMenuItem;
@property NSMenu *machinesSubmenu;
@property NSMenuItem *statusSubmenuItem;
@property NSMenu *statusSubmenu;
@property NSMenuItem *aboutMenuItem;
@property NSMenuItem *lastResetMenuItem;
@property NSMenuItem *logFileMenuItem;
@property NSMenuItem *autoHealMenuItem;
@property NSMenuItem *notificationsMenuItem;
@property NSMenuItem *syncResetMenuItem;
@property NSMenuItem *sleepSyncMenuItem;
@property NSMenuItem *sleepDisplaysSyncMenuItem;
@property NSMenuItem *logWatchMenuItem;
@property NSMenuItem *tcpWatchMenuItem;
@property NSMenuItem *launchAtLoginMenuItem;
@property NSTimer *healthTimer;
@property NSTimer *heartbeatTimer;
@property NSTask *logTask;
@property BOOL autoHealEnabled;
@property BOOL notificationsEnabled;
@property BOOL syncResetEnabled;
@property BOOL sleepSyncEnabled;
@property BOOL sleepDisplaysSyncEnabled;
@property BOOL logWatchEnabled;
@property BOOL tcpWatchEnabled;
@property BOOL heartbeatPeerHasBeenSeen;
@property BOOL tcpLinkHasBeenSeen;
@property BOOL resetInProgress;
@property NSString *instanceID;
@property NSMutableDictionary<NSString *, NSMutableDictionary<NSString *, id> *> *heartbeatPeers;
@property BOOL lastUniversalControlRunning;
@property BOOL hasLastUniversalControlRunning;
@property NSInteger lastLoggedUCConnectionCount;
@property NSInteger lastLoggedRapportLinkLocalCount;
@property NSInteger lastLoggedHeartbeatPeerCount;
@property NSString *lastLoggedPeerSummary;
@property NSInteger missedHeartbeatChecks;
@property NSMutableSet<NSString *> *ucPeersEverSeen;
@property NSMutableDictionary<NSString *, NSDate *> *ucPeersLastSeen;
@property NSDate *ucPeersLastPersistedAt;
@property NSDate *lastHeartbeatPruneAt;
@property NSDate *lastBonjourResolveAt;
@property NSMutableDictionary<NSString *, NSString *> *resolvedHostnamesByAddress;
@property NSMutableDictionary<NSString *, NSDate *> *hostnameLookupAttemptedAt;
@property NSString *lastMachineFoldState;
@property NSMutableSet<NSNumber *> *ucInterfaceScopes;
@property NSMutableOrderedSet<NSString *> *recentRemoteResetNonces;
@property NSMutableDictionary<NSString *, NSDate *> *recentRemoteResetNonceAt;
@property NSMutableOrderedSet<NSString *> *recentRemoteSleepNonces;
@property NSMutableDictionary<NSString *, NSDate *> *recentRemoteSleepNonceAt;
@property NSDate *suppressSleepBroadcastUntil;
@property NSDate *suppressDisplaysSleepBroadcastUntil;
@property NSNetService *bonjourService;
@property NSNetServiceBrowser *bonjourBrowser;
@property NSMutableDictionary<NSString *, NSNetService *> *bonjourPeers;
@property NSMutableDictionary<NSString *, NSArray<NSData *> *> *bonjourPeerAddresses;
@property int heartbeatSocket;
@property NSDate *lastResetAttempt;
@property NSDate *lastWeakResetAttempt;
@property NSDate *lastFailureLogAt;
@property NSDate *lastHeartbeatReceivedAt;
@property NSDate *resetGraceUntil;
@property NSDate *wakeAt;
@property NSInteger failureLogHits;
@property NSInteger missedTCPChecks;
@property NSInteger missedProcessChecks;
@property NSMutableArray<NSMutableDictionary<NSString *, id> *> *failureLogEvents;
@property double failureLogScore;
@property NSMutableDictionary<NSString *, NSDate *> *recentLogMessageHashes;
@property NSString *lastFailureLogLine;
@property NSMutableArray<NSNumber *> *diagPgrepSamples;
@property NSMutableArray<NSNumber *> *diagTCPSamples;
@property NSMutableArray<NSNumber *> *diagHeartbeatPeerSamples;
@property NSMenuItem *diagnosticMenuItem;
@property NSMenu *diagnosticSubmenu;
@property NSMenuItem *diagPgrepItem;
@property NSMenuItem *diagTCPItem;
@property NSMenuItem *diagHeartbeatItem;
@property NSMenuItem *diagFailureScoreItem;
@property NSMenuItem *diagRecentLineItem;
@end

@interface UplinCApp (Internal)
- (void)applicationDidFinishLaunching:(NSNotification *)notification;
- (void)applicationWillTerminate:(NSNotification *)notification;
- (void)configureMenu;
- (void)configureNotifications;
- (void)startHealthTimer;
- (void)startHeartbeatTimer;
- (void)heartbeatTick;
- (void)checkHealth;
- (void)startLogWatcher;
- (void)stopLogWatcher;
- (void)handleLog:(NSString *)text;
- (void)resetNow:(id)sender;
- (void)toggleAutoHeal:(id)sender;
- (void)toggleNotifications:(id)sender;
- (void)toggleSyncReset:(id)sender;
- (void)toggleSleepSync:(id)sender;
- (void)toggleSleepDisplaysSync:(id)sender;
- (void)toggleLogWatch:(id)sender;
- (void)toggleTCPWatch:(id)sender;
- (void)toggleLaunchAtLogin:(id)sender;
- (void)openLogFile:(id)sender;
- (void)showAboutDialog:(id)sender;
- (void)quit:(id)sender;
- (void)updateToggleStates;
- (BOOL)canAutoReset;
- (void)configureIdentity;
- (void)checkTCPLinkHealth;
- (void)checkHeartbeatHealth;
- (void)resetUniversalControl:(NSString *)reason force:(BOOL)force weak:(BOOL)isWeak manual:(BOOL)manual broadcast:(BOOL)broadcast;
- (void)handleSystemDidWake:(NSNotification *)note;
- (void)handleSystemWillSleep:(NSNotification *)note;
- (void)handleScreensDidSleep:(NSNotification *)note;
- (void)sendSleepCommandViaBonjour:(NSString *)mode;
- (void)handleRemoteSleepPayload:(NSString *)payload fromAddress:(NSString *)senderAddressString senderHost:(NSString *)senderHost;
- (void)performLocalSystemSleep;
- (void)performLocalDisplaysSleep;
- (BOOL)isInResetGrace;
- (BOOL)isInPostWakeGrace;
- (void)clearTransientHealthCounters;
- (void)startHeartbeatSocket;
- (void)stopHeartbeatSocket;
- (void)startBonjour;
- (void)stopBonjour;
- (void)netServiceDidPublish:(NSNetService *)sender;
- (void)netService:(NSNetService *)sender didNotPublish:(NSDictionary<NSString *, NSNumber *> *)errorDict;
- (void)netServiceDidResolveAddress:(NSNetService *)sender;
- (void)netService:(NSNetService *)sender didNotResolve:(NSDictionary<NSString *, NSNumber *> *)errorDict;
- (void)netServiceBrowser:(NSNetServiceBrowser *)browser didFindService:(NSNetService *)service moreComing:(BOOL)moreComing;
- (void)netServiceBrowser:(NSNetServiceBrowser *)browser didRemoveService:(NSNetService *)service moreComing:(BOOL)moreComing;
- (void)netServiceBrowser:(NSNetServiceBrowser *)browser didNotSearch:(NSDictionary<NSString *, NSNumber *> *)errorDict;
- (NSInteger)sendHeartbeatViaBonjour;
- (void)refreshBonjourResolutionsIfNeeded;
- (void)resolveHostnameForAddressIfNeeded:(NSString *)address;
- (void)copyAddressFromMenuItem:(id)sender;
- (void)sendResetCommandViaBonjour:(NSString *)reason;
- (void)drainHeartbeatSocket;
- (NSString *)canonicalizedAddressFromSockaddr:(const struct sockaddr *)sa;
- (void)handleRemoteResetPayload:(NSString *)payload fromAddress:(NSString *)senderAddressString senderHost:(NSString *)senderHost;
- (NSDictionary<NSString *, NSString *> *)heartbeatFieldsFromPayload:(NSString *)payload;
- (NSArray<NSDictionary<NSString *, id> *> *)recentHeartbeatPeers;
- (NSArray<NSDictionary<NSString *, id> *> *)allKnownMachines;
- (NSString *)formatPeerAge:(NSTimeInterval)age;
- (void)updatePeerStatusWithUCPeerAddresses:(NSArray<NSString *> *)ucPeerAddresses;
- (void)rebuildMachinesSubmenu;
- (NSImage *)machineIndicatorImageWithHeartbeat:(BOOL)hasHeartbeat
                                universalControl:(BOOL)hasUniversalControl
                                          online:(BOOL)isOnline;
- (NSString *)compactAddress:(NSString *)address;
- (NSString *)sanitizedToken:(NSString *)value;
- (void)setStatusIcon:(NSString *)symbolName fallbackTitle:(NSString *)fallbackTitle description:(NSString *)description;
- (NSString *)formattedTime:(NSDate *)date;
- (NSString *)logPath;
- (void)appendLog:(NSString *)message;
- (void)ensureLogFileExists;
- (void)rotateLogIfNeeded;
- (NSString *)logTimestamp;
- (NSString *)sanitizedSingleLine:(NSString *)text maxLength:(NSUInteger)maxLength;
- (void)notifyResetComplete:(NSString *)reason manual:(BOOL)manual;
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler;
- (BOOL)isProcessRunning:(NSString *)name;
- (void)getTCPConnectionCount:(NSInteger *)ucConnectionCount rapportLinkLocalCount:(NSInteger *)rapportLinkLocalCount ucIncompleteCount:(NSInteger *)ucIncompleteCount ucPeerAddresses:(NSArray<NSString *> **)ucPeerAddresses;
- (NSArray<NSString *> *)universalControlPeerAddresses;
- (NSString *)peerAddressFromLsofLine:(NSString *)line;
- (BOOL)parseIPv6Address:(NSString *)addressString into:(struct in6_addr *)outAddr scopeID:(uint32_t *)outScopeID;
- (NSString *)formatIPv6Address:(const struct in6_addr *)addr scopeID:(uint32_t)scopeID;
- (NSString *)canonicalIPv6String:(NSString *)addressString;
- (void)loadUCPeersFromDefaults;
- (void)saveUCPeersToDefaults;
- (void)noteUCPeerSeen:(NSString *)canonicalAddress;
- (void)pruneStaleHeartbeatPeers;
- (void)recordDiagnosticTick;
- (void)rebuildDiagnosticSubmenu;
- (void)pruneFailureLogWindow;
- (int)run:(NSString *)executable arguments:(NSArray<NSString *> *)arguments;
- (NSString *)outputFrom:(NSString *)executable arguments:(NSArray<NSString *> *)arguments;
@end
